name: Feature Request
description: Suggest an idea for VersaUI
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      options:
        - Widgets
        - Layouts
        - Themes
        - Events
        - Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this feature solve?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered? 